### ISSUE TITLE
Instructions to create the environment missing

### ISSUE THREAD

**Issue by macneves** [MolecularAI/QSARtuna#16]
Hello.
Could you please share the instructions to create the environment?
Thanks

**Comment by lewismervin1** [comment]
Please can you consult this section of the README:

https://github.com/MolecularAI/QSARtuna/tree/3.1.1?tab=readme-ov-file#run-from-pythonjupyter-notebook

and let me know if this resolves your issue?

**Comment by lewismervin1** [comment]
I will close as the README was improved
