### ISSUE TITLE
Question about adding custom descriptor calculation method

### ISSUE THREAD

**Issue by hirose125** [MolecularAI/QSARtuna#17]
Hello 

Thank you for the wonderful package. 
I would like to definitely make use of it for utilizing MLOps.

Is it possible to integrate a custom descriptor calculation library into this library?

**Comment by lewismervin1** [comment]
Hello,

I have added some instructions as part of https://github.com/MolecularAI/QSARtuna/pull/18. 

Please check the new 3.1.1 readme for instructions on custom calculation within QSARtuna: https://github.com/MolecularAI/QSARtuna/tree/3.1.1?tab=readme-ov-file#adding-descriptors-to-qsartuna

**Comment by hirose125** [comment]
Hello 

Thank you for responce.
I miss the documentation.
I try to add new representation.
