### ISSUE TITLE
Install instruction on conda has link to AZ server failing

### ISSUE THREAD

**Issue by jeremycheminf** [MolecularAI/QSARtuna#2]
The installation to run the tool with a notebook has this line
python -m pip install http://pages.scp.astrazeneca.net/mai/qptuna/releases/Qptuna_latest.tar.gz
but when running it, it gives error to access the file

**Comment by WoutVanEynde** [comment]
Have you resolved this problem?

**Comment by jeremycheminf** [comment]
Hi
I managed via cloning the repo and then run poetry install 👍

**Comment by WoutVanEynde** [comment]
Alright, thank you!
