### ISSUE TITLE
Output of training and testing sets

### ISSUE THREAD

**Issue by kong0706** [MolecularAI/QSARtuna#22]
Hello, I created the QSARtuna configuration in Python and set up a dataset splitting strategy. How do I output the training and testing set files? Looking forward to your response.

**Comment by lewismervin1** [comment]
Hello, thanks for the interest in QSARtuna. You may use the `intermediate_test_dataset_file` and `intermediate_training_dataset_file` within the "data" section of the JSON or configuration options, like so:

`
  "data": {
    "training_dataset_file": "input.csv",
    "input_column": "SMILES",
    "response_column": "ACTIVITY",
    "response_type": "regression",
    "save_intermediate_files": true,
    "intermediate_test_dataset_file": "./ST00010.csv.intermediate_test_dataset_file.csv",
    "intermediate_training_dataset_file": "./ST00010.csv.intermediate_training_dataset_file.csv",
  }
