### ISSUE TITLE
Does QSARtuna Utilize GPU Resources?

### ISSUE THREAD

**Issue by sasaju** [MolecularAI/QSARtuna#23]
I noticed that the project uses PyTorch, but during execution, I observed that my GPU was not being utilized. Is additional configuration required to enable GPU acceleration?

CPU: AMD 5600G
GPU: GTX1060 6G
CUDA Version: CUDA 12.2
Driver Version: 535.183.01

```
import torch
torch.cuda.is_available()
# True
```

**Comment by lewismervin1** [comment]
Thanks for the interest in QSARtuna and the PR @sasaju. QSARtuna will utilise GPU or the MPS backend (on OSX) when training the ChemProp algorithm. No additional configuration should be necessary. It might be that you checked the GPU utilisation stats when QSARtuna was not actively training the network. Please can you check once the logs are showing that ChemProp trials are being evaluated by Optuna (toward the end of the run if using split_chemprop=True, e.g. see https://molecularai.github.io/QSARtuna/notebooks/QSARtuna_Tutorial.html#ChemProp-optimization-separate-from-shallow-methods-(default-behavior))

**Comment by lewismervin1** [comment]
Hi @sasaju , were you able to get QSARtuna working with GPUs?

**Comment by sasaju** [comment]
I have run it correctly. I was busy some time ago and forgot to reply. This program is very useful! Thank you for the software and help.
