### ISSUE TITLE
Is it possible to add other ML algorithms?

### ISSUE THREAD

**Issue by Henrik51** [MolecularAI/QSARtuna#25]
Hello,

thanks for the great package! I am wondering if and how it is possible to add other ML algorithms? 

Thanks a lot in advance!

**Comment by lewismervin1** [comment]
Hi @Henrik51. Thanks for the interest in QSARtuna. I have updated the README as part of 3.1.2 to include instructions to add ML algorithms: https://github.com/MolecularAI/QSARtuna/blob/master/README.md#adding-machine-learning-algorithms-to-qsartuna.

Please have a look and see if it enables you to add another ML algorithm?

**Comment by lewismervin1** [comment]
Hi @Henrik51, were you able to add the machine learning algorithm that you wanted? I was wondering which ML algorithm are you trying to implement? It may help to improve QSARtuna if it was added?

**Comment by Henrik51** [comment]
Hi @lewismervin1,

Thank you a lot for adding the part to the README. It is very clearly explained. I have not had the chance to try it out yet. I will let you know when I have. I want to add Mordred descriptors and Gaussian Process Regressor.

**Comment by lewismervin1** [comment]
Hi @Henrik51, I added CustomRegressionModel and CustromClassifiationModel to the algorithms which allow to use existing .pkl files at Optimisation and Build time: https://molecularai.github.io/QSARtuna/notebooks/QSARtuna_Tutorial.html#Preexisting-models:-Convert-scikit-learn(-like)-models-to-QSARtuna-models and you can also use them at optimisation or build time: https://molecularai.github.io/QSARtuna/notebooks/QSARtuna_Tutorial.html#Preexisting-models:-Using-prexisting-models-as-custom-models-for-Optimisation-or-Build with the option to refit algorithms or not. 

This should help to add external methods into QSARtuna (though still experimental).  You will need to install any packages not installed by QSARtuna into the same environment. 

Let me know if this helps or if you have any suggestions for this functionality.
