### ISSUE TITLE
Convert trained sklearn model to QSARTuna model.

### ISSUE THREAD

**Issue by JanoschMenke** [MolecularAI/QSARtuna#26]
Hey,

is there an easy way to convert an existing sklearn model into a QSARTuna model. I guess I would have to load the model file as well as the parameters for the input descriptors.

Best

**Comment by halx** [comment]
Yes, it would be good to have an answer to this question and explain this in the README @lewismervin1 @alexvoronov .

**Comment by lewismervin1** [comment]
Hi @halx and @JanoschMenke,

QSARtuna 3.1.4 now has a convert CLI and notebook function to perform conversion of sklearn like models to QSARtuna models. More information is in the [README](https://github.com/MolecularAI/QSARtuna/tree/master?tab=readme-ov-file#converting-models-to-qsartuna-models) and [Notebook](https://molecularai.github.io/QSARtuna/notebooks/QSARtuna_Tutorial.html#Preexisting-models:-Convert-scikit-learn(-like)-models-to-QSARtuna-models). Let me know if you have any questions

**Comment by halx** [comment]
Many thanks, Lewis.

**Comment by lewismervin1** [comment]
@JanoschMenke hope this helps- let me know if you have any feedback on the convert functions

**Comment by JanoschMenke** [comment]
Hi sorry yes thanks a lot for addressing this issue.
