### ISSUE TITLE
for Choosing scoring function, how to set OptimizationDirection

### ISSUE THREAD

**Issue by MachineGUN001** [MolecularAI/QSARtuna#6]
To improve the accuracy and performance of the model. In QPTUNA, for training when neg_mean_absolute_error is used as the objective, should **minimization or maximization** be chosen as the optimization direction?

```
    settings=OptimizationConfig.Settings(
        mode=ModelMode.REGRESSION,
        cross_validation=3,
        n_trials=100,
        n_startup_trials=50,
        scoring="neg_mean_absolute_error",  # Scoring function name from scikit-learn.
        direction=OptimizationDirection.MAXIMIZATION, # MAXIMIZATION or Minimization?
        track_to_mlflow=False,
```

many thanks,

**Comment by lewismervin1** [comment]
Thanks for the interest in Qptuna. The default scoring function "neg_mean_absolute_error" is the **negated** mean absolute error, so larger (albeit negative) values are better. You should use the maximise direction "OptimizationDirection.MAXIMIZATION" for your chosen direction.

**Comment by MachineGUN001** [comment]
got it. thanks for your kind explanation.
